const constants = {
  APP_NAME: "MergeMate",
  TAG_LINE: "Connecting Coders, Empowering Open Source",
};

export const TechStacks = [
  "React",
  "Next.js",
  "Vue.js",
  "Nuxt.js",
  "Angular",
  "Svelte",
  "Gatsby",
  "TypeScript",
  "JavaScript (ES6+)",
  "TailwindCSS",
  "Bootstrap",
  "Material-UI (MUI)",
  "Chakra UI",
  "SCSS/SASS",
  "Styled Components",

  "Node.js",
  "Express.js",
  "NestJS",
  "Django",
  "Flask",
  "Ruby on Rails",
  "Spring Boot",
  "Laravel",
  "Fastify",
  "Koa.js",
  "ASP.NET Core",
  "Go (Gin, Echo)",
  "Hapi.js",

  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "Redis",
  "Cassandra",
  "DynamoDB",
  "Firebase Firestore",
  "MariaDB",
  "Elasticsearch",
  "CouchDB",

  "GraphQL",
  "Apollo Server",
  "REST API",
  "gRPC",
  "JSON-RPC",
  "Swagger/OpenAPI",
  "Postman",

  "Jest",
  "Mocha",
  "Chai",
  "Cypress",
  "Puppeteer",
  "Playwright",
  "Enzyme",
  "React Testing Library",
  "Selenium",
  "Karma",
  "Jasmine",

  "GitHub Actions",
  "GitLab CI/CD",
  "CircleCI",
  "Travis CI",
  "Jenkins",
  "Bitbucket Pipelines",
  "Azure DevOps",
  "ArgoCD",
  "TeamCity",

  "Docker",
  "Kubernetes",
  "Docker Compose",
  "OpenShift",
  "Helm",
  "Nomad",
  "Rancher",

  "AWS (S3, EC2, Lambda, etc.)",
  "Google Cloud Platform (GCP)",
  "Microsoft Azure",
  "Firebase",
  "DigitalOcean",
  "Heroku",
  "Vercel",
  "Netlify",
];

export const techStackOptions = TechStacks.map((tech) => ({
  value: tech,
  label: tech,
}));

export default constants;
